/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.beastiebots.scouting.gui;

import java.nio.file.Files;
import net.samuelcampos.usbdrivedectector.USBStorageDevice;
import org.beastiebots.scouting.tournament.MatchData;
import org.beastiebots.scouting.tournament.Team;
import org.beastiebots.scouting.tournament.TeleopPerformance;
import org.beastiebots.scouting.tournament.Tournament;
import org.beastiebots.scouting.tournament.uploader.ScoutingClient;

/**
 *
 * @author Jacob
 */
public class ScoutingObjectiveClientUI extends javax.swing.JFrame {

    Tournament tournament;
    USBStorageDevice flashDrive;

    /**
     * Creates new form ScoutingClientUI
     */
    public ScoutingObjectiveClientUI() {
        initComponents();
        tournament = new Tournament();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        teleopPerformance1 = new org.beastiebots.scouting.tournament.TeleopPerformance();
        teleopPerformance2 = new org.beastiebots.scouting.tournament.TeleopPerformance();
        jLabel1 = new javax.swing.JLabel();
        commitButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        teamNumber1 = new javax.swing.JTextField();
        teamNumber2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldPanel2 = new org.beastiebots.scouting.autonomousPlotter.FieldPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldPanel1 = new org.beastiebots.scouting.autonomousPlotter.FieldPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        checkBoxHang1 = new javax.swing.JCheckBox();
        checkBoxDoubleHang1 = new javax.swing.JCheckBox();
        checkBoxFlag1 = new javax.swing.JCheckBox();
        spinnerAutoCube1 = new javax.swing.JSpinner();
        spinnerTeleopCubes1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        checkBoxHang2 = new javax.swing.JCheckBox();
        spinnerAutoCube2 = new javax.swing.JSpinner();
        checkBoxFlag2 = new javax.swing.JCheckBox();
        checkBoxDoubleHang2 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        spinnerTeleopCubes2 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxDoubleHang1, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance1, org.jdesktop.beansbinding.BeanProperty.create("doubleHang"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxFlag1, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance1, org.jdesktop.beansbinding.BeanProperty.create("flag"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxHang1, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance1, org.jdesktop.beansbinding.BeanProperty.create("hang"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, spinnerTeleopCubes1, org.jdesktop.beansbinding.ELProperty.create("${value}"), teleopPerformance1, org.jdesktop.beansbinding.BeanProperty.create("numCubes"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxDoubleHang2, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance2, org.jdesktop.beansbinding.BeanProperty.create("doubleHang"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxFlag2, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance2, org.jdesktop.beansbinding.BeanProperty.create("flag"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, checkBoxHang2, org.jdesktop.beansbinding.ELProperty.create("${selected}"), teleopPerformance2, org.jdesktop.beansbinding.BeanProperty.create("hang"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, spinnerTeleopCubes2, org.jdesktop.beansbinding.ELProperty.create("${value}"), teleopPerformance2, org.jdesktop.beansbinding.BeanProperty.create("numCubes"));
        bindingGroup.addBinding(binding);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Match number:");

        commitButton.setText("Commit");
        commitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtonActionPerformed(evt);
            }
        });

        teamNumber1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teamNumber1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamNumber1FocusGained(evt);
            }
        });

        teamNumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        teamNumber2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamNumber2FocusGained(evt);
            }
        });

        jLabel3.setText("Team number:");

        jLabel2.setText("Team number:");

        fieldPanel2.setMult(1.0);
        fieldPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("4");
        fieldPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 173, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("3");
        fieldPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 160, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("2");
        fieldPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 142, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("1");
        fieldPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 128, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("1");
        fieldPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 97, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("2");
        fieldPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 84, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("3");
        fieldPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 66, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("4");
        fieldPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 52, -1, -1));

        fieldPanel1.setMult(1.0);
        fieldPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1");
        fieldPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 99, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2");
        fieldPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 86, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3");
        fieldPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 68, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4");
        fieldPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 54, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("4");
        fieldPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 173, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("3");
        fieldPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 160, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("2");
        fieldPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 142, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1");
        fieldPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 128, -1, -1));

        checkBoxHang1.setText("Hang");

        checkBoxDoubleHang1.setText("Double Hang");

        checkBoxFlag1.setText("Flag");

        spinnerAutoCube1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        spinnerAutoCube1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAutoCube1StateChanged(evt);
            }
        });

        spinnerTeleopCubes1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabel4.setText("Auto cube:");

        jLabel21.setText("Approx teleop cubes:");

        jLabel22.setText("Endgame:");

        jLabel23.setText("Auto cube:");

        checkBoxHang2.setText("Hang");

        spinnerAutoCube2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        spinnerAutoCube2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAutoCube2StateChanged(evt);
            }
        });

        checkBoxFlag2.setText("Flag");

        checkBoxDoubleHang2.setText("Double Hang");

        jLabel24.setText("Approx teleop cubes:");

        spinnerTeleopCubes2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabel25.setText("Endgame:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(fieldPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(teamNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxHang1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxDoubleHang1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxFlag1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAutoCube1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerTeleopCubes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerAutoCube2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerTeleopCubes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(teamNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fieldPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkBoxHang2)
                                        .addGap(6, 6, 6)
                                        .addComponent(checkBoxDoubleHang2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkBoxFlag2)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(commitButton))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinnerTeleopCubes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spinnerAutoCube1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(spinnerAutoCube2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(spinnerTeleopCubes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxHang1)
                    .addComponent(checkBoxDoubleHang1)
                    .addComponent(checkBoxFlag1)
                    .addComponent(checkBoxHang2)
                    .addComponent(checkBoxDoubleHang2)
                    .addComponent(checkBoxFlag2))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void commitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitButtonActionPerformed
        FlashDriveChooser selector = new FlashDriveChooser(this, true, flashDrive);
        selector.setVisible(true);
        if (flashDrive == null || Files.notExists(flashDrive.getRootDirectory().toPath())) {
            flashDrive = null;
        }
        flashDrive = selector.getChosenDevice();
        if (!teamNumber1.getText().isEmpty()) {
            Team team1 = tournament.getOrCreateTeamByNumber(Integer.parseInt(teamNumber1.getText()));
            team1.addMatchData(new MatchData(jTextField1.getText(), fieldPanel1.getAutonomousRoutine(), TeleopPerformance.createTeleopPerformance(teleopPerformance1)));
        }
        if (!teamNumber2.getText().isEmpty()) {
            Team team2 = tournament.getOrCreateTeamByNumber(Integer.parseInt(teamNumber2.getText()));
            team2.addMatchData(new MatchData(jTextField1.getText(), fieldPanel2.getAutonomousRoutine(), TeleopPerformance.createTeleopPerformance(teleopPerformance2)));
        }
        teamNumber1.setText("");
        teamNumber2.setText("");
        fieldPanel1.reset();
        fieldPanel2.reset();
        boolean is_number = true;
        int matchNumber = 0;
        try {
            matchNumber = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            is_number = false;
        }
        if (is_number) {
            jTextField1.setText(Integer.toString(matchNumber + 1));
        } else {
            jTextField1.setText("");
        }
        System.out.println(tournament.toJson().toString());
        (new ScoutingClient(tournament.toJson().toString(),(flashDrive != null)?flashDrive.getRootDirectory().toPath():null)).execute();
    }//GEN-LAST:event_commitButtonActionPerformed

    private void teamNumber1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamNumber1FocusGained
        teamNumber1.setSelectionStart(0);
    }//GEN-LAST:event_teamNumber1FocusGained

    private void teamNumber2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamNumber2FocusGained
        teamNumber2.setSelectionStart(0);
    }//GEN-LAST:event_teamNumber2FocusGained

    private void spinnerAutoCube1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAutoCube1StateChanged
        fieldPanel1.getAutonomousRoutine().setGoal((Integer)spinnerAutoCube1.getValue());
    }//GEN-LAST:event_spinnerAutoCube1StateChanged

    private void spinnerAutoCube2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAutoCube2StateChanged
        fieldPanel2.getAutonomousRoutine().setGoal((Integer)spinnerAutoCube2.getValue());
    }//GEN-LAST:event_spinnerAutoCube2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoutingObjectiveClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoutingObjectiveClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoutingObjectiveClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoutingObjectiveClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoutingObjectiveClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxDoubleHang1;
    private javax.swing.JCheckBox checkBoxDoubleHang2;
    private javax.swing.JCheckBox checkBoxFlag1;
    private javax.swing.JCheckBox checkBoxFlag2;
    private javax.swing.JCheckBox checkBoxHang1;
    private javax.swing.JCheckBox checkBoxHang2;
    private javax.swing.JButton commitButton;
    private org.beastiebots.scouting.autonomousPlotter.FieldPanel fieldPanel1;
    private org.beastiebots.scouting.autonomousPlotter.FieldPanel fieldPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner spinnerAutoCube1;
    private javax.swing.JSpinner spinnerAutoCube2;
    private javax.swing.JSpinner spinnerTeleopCubes1;
    private javax.swing.JSpinner spinnerTeleopCubes2;
    private javax.swing.JTextField teamNumber1;
    private javax.swing.JTextField teamNumber2;
    private org.beastiebots.scouting.tournament.TeleopPerformance teleopPerformance1;
    private org.beastiebots.scouting.tournament.TeleopPerformance teleopPerformance2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
